
name: Build Supermark Site
on: [push]
jobs:
  Build-Supermark:
    runs-on: ubuntu-latest
    steps:
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            supermark
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pandoc
        run: |
          $CONDA/bin/conda install pandoc
          ln -s $CONDA/bin/pandoc /usr/local/bin/pandoc
      - name: Run Supermark
        run: |
          supermark build --all --log --verbose
      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo ::set-output name=uid::$actions_user_id
      - name: Push
        uses: actions-x/commit@v6
